name: CI

on:
  push:
    branches:
      - master

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add To GitHub projects
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: ""       # URL of the project to add issues to
          github-token: ""      # A GitHub personal access token with write access to the project
          labeled: ""           # A comma-separated list of labels to use as a filter for issue to be added (optional)
          label-operator: ""    # The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR) (optional)
